"""
Base Analysis Type Abstract Class

Defines the interface that all climate analysis types must implement.
This enables extensibility for new climate conditions like ice melting,
flooding, drought, etc.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional
import numpy as np


class Severity(str, Enum):
    """Alert severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class Alert:
    """
    Represents an alert generated by analysis.
    
    Attributes:
        alert_type: Type of alert (e.g., "deforestation_detected", "ice_loss_critical")
        severity: Severity level of the alert
        title: Short title for the alert
        message: Detailed message describing the alert
        details: Additional structured data
        threshold_exceeded: The threshold that was exceeded (if applicable)
        measured_value: The actual measured value
    """
    alert_type: str
    severity: Severity
    title: str
    message: str
    details: dict[str, Any] = field(default_factory=dict)
    threshold_exceeded: Optional[float] = None
    measured_value: Optional[float] = None


@dataclass
class AnalysisResult:
    """
    Standardized result from analysis.
    
    Attributes:
        analysis_type: Name of the analysis type
        success: Whether analysis completed successfully
        region: Region information (bbox, date range, etc.)
        metrics: Analysis-specific metrics
        confidence: Overall confidence score (0-1)
        alerts: List of generated alerts
        mask: Optional segmentation mask
        error: Error message if analysis failed
    """
    analysis_type: str
    success: bool
    region: dict[str, Any] = field(default_factory=dict)
    metrics: dict[str, Any] = field(default_factory=dict)
    confidence: float = 0.0
    alerts: list[Alert] = field(default_factory=list)
    mask: Optional[np.ndarray] = None
    error: Optional[str] = None
    
    def to_dict(self) -> dict[str, Any]:
        """Convert result to dictionary for JSON serialization."""
        result = {
            "analysis_type": self.analysis_type,
            "success": self.success,
            "region": self.region,
            "inference": {
                **self.metrics,
                "mean_confidence": self.confidence,
            },
        }
        
        if self.error:
            result["error"] = self.error
        
        if self.alerts:
            result["alerts"] = [
                {
                    "type": alert.alert_type,
                    "severity": alert.severity.value,
                    "title": alert.title,
                    "message": alert.message,
                }
                for alert in self.alerts
            ]
        
        return result


class BaseAnalysisType(ABC):
    """
    Abstract base class for all climate analysis types.
    
    To create a new analysis type:
    1. Subclass BaseAnalysisType
    2. Implement all abstract methods
    3. Register with the analysis registry
    
    Example:
        class MyAnalysis(BaseAnalysisType):
            name = "my_analysis"
            display_name = "My Custom Analysis"
            ...
    """
    
    # Class attributes to be overridden
    name: str = ""
    display_name: str = ""
    description: str = ""
    
    # Required satellite bands
    required_bands: list[str] = []
    
    # Output classification classes
    output_classes: list[str] = []
    
    # Whether this analysis type is currently enabled
    enabled: bool = True
    
    # Default alert thresholds
    default_thresholds: dict[str, float] = {}
    
    @abstractmethod
    def preprocess(
        self,
        image: np.ndarray,
        bands: Optional[list[str]] = None,
    ) -> np.ndarray:
        """
        Preprocess input image for model inference.
        
        Args:
            image: Input image array (H, W, C) or (C, H, W)
            bands: List of band names in the input image
        
        Returns:
            Preprocessed image array ready for inference
        """
        pass
    
    @abstractmethod
    def run_inference(
        self,
        image: np.ndarray,
        model: Optional[Any] = None,
    ) -> tuple[np.ndarray, float]:
        """
        Run model inference on preprocessed image.
        
        Args:
            image: Preprocessed image array
            model: Optional pre-loaded model (uses default if None)
        
        Returns:
            Tuple of (prediction_mask, confidence_score)
        """
        pass
    
    @abstractmethod
    def calculate_metrics(
        self,
        prediction: np.ndarray,
        image_size: tuple[int, int],
        bbox: Optional[list[float]] = None,
    ) -> dict[str, Any]:
        """
        Calculate analysis-specific metrics from prediction.
        
        Args:
            prediction: Prediction mask array
            image_size: Original image dimensions (height, width)
            bbox: Optional bounding box for area calculations
        
        Returns:
            Dictionary of calculated metrics
        """
        pass
    
    @abstractmethod
    def generate_alerts(
        self,
        metrics: dict[str, Any],
        thresholds: Optional[dict[str, float]] = None,
        previous_metrics: Optional[dict[str, Any]] = None,
    ) -> list[Alert]:
        """
        Generate alerts based on metrics and thresholds.
        
        Args:
            metrics: Current analysis metrics
            thresholds: Alert thresholds (uses defaults if None)
            previous_metrics: Previous analysis metrics for comparison
        
        Returns:
            List of generated alerts
        """
        pass
    
    def analyze(
        self,
        image: np.ndarray,
        bbox: Optional[list[float]] = None,
        date_range: Optional[str] = None,
        thresholds: Optional[dict[str, float]] = None,
        previous_metrics: Optional[dict[str, Any]] = None,
        model: Optional[Any] = None,
    ) -> AnalysisResult:
        """
        Run complete analysis pipeline.
        
        This method orchestrates preprocessing, inference, metric calculation,
        and alert generation. Override individual methods to customize behavior.
        
        Args:
            image: Input satellite image
            bbox: Geographic bounding box [minLon, minLat, maxLon, maxLat]
            date_range: Date range string for the analysis
            thresholds: Custom alert thresholds
            previous_metrics: Previous metrics for change detection
            model: Optional pre-loaded model
        
        Returns:
            AnalysisResult containing all analysis outputs
        """
        try:
            # Get image dimensions
            if image.ndim == 3:
                if image.shape[0] < image.shape[2]:
                    # (C, H, W) format
                    h, w = image.shape[1], image.shape[2]
                else:
                    # (H, W, C) format
                    h, w = image.shape[0], image.shape[1]
            else:
                h, w = image.shape[:2]
            
            # Preprocess
            preprocessed = self.preprocess(image)
            
            # Run inference
            prediction, confidence = self.run_inference(preprocessed, model)
            
            # Calculate metrics
            metrics = self.calculate_metrics(prediction, (h, w), bbox)
            
            # Generate alerts
            alerts = self.generate_alerts(metrics, thresholds, previous_metrics)
            
            # Build region info
            region = {}
            if bbox:
                region["bbox"] = bbox
            if date_range:
                region["date_range"] = date_range
            
            return AnalysisResult(
                analysis_type=self.name,
                success=True,
                region=region,
                metrics=metrics,
                confidence=confidence,
                alerts=alerts,
                mask=prediction,
            )
            
        except Exception as e:
            return AnalysisResult(
                analysis_type=self.name,
                success=False,
                error=str(e),
            )
    
    def get_info(self) -> dict[str, Any]:
        """Get information about this analysis type."""
        return {
            "name": self.name,
            "display_name": self.display_name,
            "description": self.description,
            "required_bands": self.required_bands,
            "output_classes": self.output_classes,
            "enabled": self.enabled,
            "default_thresholds": self.default_thresholds,
        }
    
    def validate_input(self, image: np.ndarray) -> tuple[bool, str]:
        """
        Validate input image.
        
        Args:
            image: Input image array
        
        Returns:
            Tuple of (is_valid, error_message)
        """
        if image is None:
            return False, "Image is None"
        
        if not isinstance(image, np.ndarray):
            return False, f"Expected numpy array, got {type(image)}"
        
        if image.ndim < 2 or image.ndim > 4:
            return False, f"Expected 2-4 dimensional array, got {image.ndim}"
        
        if image.size == 0:
            return False, "Image is empty"
        
        return True, ""
